=== rxliuli/novachat/docs/public/plugin/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "name", "version"],
  "properties": {
    "id": {
      "type": "string",
      "description": "The unique identifier for the plugin"
    },
    "name": {
      "type": "string",
      "description": "The name of the plugin"
    },
    "version": {
      "type": "string",
      "description": "The version of the plugin"
    },
    "description": {
      "type": "string",
      "description": "The description of the plugin"
    },
    "author": {
      "type": "string",
      "description": "The author of the plugin"
    },
    "homepage": {
      "type": "string",
      "description": "The homepage of the plugin"
    },
    "repository": {
      "type": "string",
      "description": "The repository of the plugin"
    },
    "lastUpdated": {
      "type": "string",
      "description": "The last updated date of the plugin"
    },
    "icons": {
      "type": "object",
      "description": "The icons of the plugin"
    },
    "configuration": {
      "type": "object",
      "description": "The configuration of the plugin",
      "$ref": "http://json-schema.org/draft-07/schema#"
    }
  }
}

=== rxliuli/novachat/packages/plugin-openai/src/plugin.json
{
  "id": "novachat.openai",
  "name": "OpenAI Provider",
  "description": "OpenAI Provider",
  "version": "0.1.1",
  "author": "NovaChat",
  "configuration": {
    "title": "OpenAI",
    "properties": {
      "openai.apiKey": {
        "type": "string",
        "description": "OpenAI API key",
        "default": "",
        "format": "password"
      }
    }
  }
}

=== rxliuli/novachat/packages/plugin-gemini/src/plugin.json
{
  "id": "novachat.gemini",
  "name": "Gemini",
  "description": "Gemini Provider",
  "version": "0.1.0",
  "configuration": {
    "title": "gemini",
    "properties": {
      "gemini.apiKey": {
        "type": "string",
        "description": "Google Generative AI API Key",
        "format": "password"
      }
    }
  }
}

=== rxliuli/novachat/packages/plugin-anthropic/src/plugin.json
{
  "id": "novachat.anthropic",
  "name": "Anthropic",
  "description": "Anthropic Provider",
  "version": "0.1.0",
  "author": "NovaChat",
  "configuration": {
    "title": "Anthropic",
    "properties": {
      "anthropic.apiKey": {
        "type": "string",
        "description": "Anthropic API Key",
        "default": ""
      }
    }
  }
}

=== rxliuli/novachat/src/lib/plugins/internal/translator/plugin.json
{
  "id": "novachat.translator",
  "name": "Translator",
  "description": "Translate text",
  "version": "0.1.0",
  "author": "NovaChat",
  "configuration": {
    "title": "Translator",
    "properties": {
      "translator.localLanguage": {
        "type": "string",
        "description": "Local language",
        "default": "eng",
        "enum": [
          "cmn",
          "spa",
          "eng",
          "rus",
          "arb",
          "ben",
          "hin",
          "por",
          "ind",
          "jpn",
          "fra",
          "deu",
          "jav",
          "jav",
          "kor",
          "tel",
          "vie",
          "mar",
          "ita",
          "tam",
          "tur",
          "urd",
          "guj",
          "pol",
          "ukr",
          "kan",
          "mai",
          "mal",
          "pes",
          "mya",
          "swh",
          "sun",
          "ron",
          "pan",
          "bho",
          "amh",
          "hau",
          "fuv",
          "bos",
          "bos",
          "hrv",
          "nld",
          "srp",
          "srp",
          "tha",
          "ckb",
          "yor",
          "uzn",
          "uzn",
          "zlm",
          "zlm",
          "ibo",
          "npi",
          "ceb",
          "skr",
          "tgl",
          "hun",
          "azj",
          "azj",
          "sin",
          "koi",
          "ell",
          "ces",
          "mag",
          "run",
          "bel",
          "plt",
          "qug",
          "mad",
          "nya",
          "zyb",
          "pbu",
          "kin",
          "zul",
          "bul",
          "swe",
          "lin",
          "som",
          "hms",
          "hnj",
          "ilo",
          "kaz"
        ],
        "enumDescriptions": [
          "Mandarin Chinese",
          "Spanish",
          "English",
          "Russian",
          "Standard Arabic",
          "Bengali",
          "Hindi",
          "Portuguese",
          "Indonesian",
          "Japanese",
          "French",
          "German",
          "Javanese (Javanese)",
          "Javanese (Latin)",
          "Korean",
          "Telugu",
          "Vietnamese",
          "Marathi",
          "Italian",
          "Tamil",
          "Turkish",
          "Urdu",
          "Gujarati",
          "Polish",
          "Ukrainian",
          "Kannada",
          "Maithili",
          "Malayalam",
          "Iranian Persian",
          "Burmese",
          "Swahili (individual language)",
          "Sundanese",
          "Romanian",
          "Panjabi",
          "Bhojpuri",
          "Amharic",
          "Hausa",
          "Nigerian Fulfulde",
          "Bosnian (Cyrillic)",
          "Bosnian (Latin)",
          "Croatian",
          "Dutch",
          "Serbian (Cyrillic)",
          "Serbian (Latin)",
          "Thai",
          "Central Kurdish",
          "Yoruba",
          "Northern Uzbek (Cyrillic)",
          "Northern Uzbek (Latin)",
          "Malay (individual language) (Arabic)",
          "Malay (individual language) (Latin)",
          "Igbo",
          "Nepali (individual language)",
          "Cebuano",
          "Saraiki",
          "Tagalog",
          "Hungarian",
          "North Azerbaijani (Cyrillic)",
          "North Azerbaijani (Latin)",
          "Sinhala",
          "Komi-Permyak",
          "Modern Greek (1453-)",
          "Czech",
          "Magahi",
          "Rundi",
          "Belarusian",
          "Plateau Malagasy",
          "Chimborazo Highland Quichua",
          "Madurese",
          "Nyanja",
          "Yongbei Zhuang",
          "Northern Pashto",
          "Kinyarwanda",
          "Zulu",
          "Bulgarian",
          "Swedish",
          "Lingala",
          "Somali",
          "Southern Qiandong Miao",
          "Hmong Njua",
          "Iloko",
          "Kazakh"
        ]
      }
    }
  }
}

=== rxliuli/novachat/packages/plugin-vertex-anthropic/src/plugin.json
{
  "id": "novachat.vertex-anthropic",
  "name": "Vertex Anthropic",
  "description": "Vertex Anthropic Provider",
  "version": "0.1.0",
  "author": "NovaChat",
  "configuration": {
    "title": "Vertex Anthropic",
    "properties": {
      "vertexAnthropic.googleSaClientEmail": {
        "type": "string",
        "description": "Google Service Account Client Email",
        "default": ""
      },
      "vertexAnthropic.googleSaPrivateKey": {
        "type": "string",
        "description": "Google Service Account Private Key",
        "default": "",
        "format": "password"
      },
      "vertexAnthropic.region": {
        "type": "string",
        "description": "Google Cloud Region",
        "default": "us-east5"
      },
      "vertexAnthropic.projectId": {
        "type": "string",
        "description": "Google Cloud Project ID",
        "default": ""
      }
    }
  }
}

=== rxliuli/novachat/src/lib/plugins/__tests__/mock/openai/plugin.json
{
  "id": "novachat.openai",
  "name": "OpenAI Provider",
  "description": "OpenAI Provider",
  "version": "0.1.0",
  "author": "NovaChat",
  "configuration": {
    "title": "OpenAI Configuration",
    "properties": {
      "openai.apiKey": {
        "type": "string",
        "description": "The API key to use for OpenAI",
        "default": ""
      },
      "openai.baseURL": {
        "type": "string",
        "description": "The API URL to use for OpenAI",
        "default": "https://api.openai.com/v1"
      }
    }
  }
}

=== rxliuli/novachat/packages/plugin-translator/src/plugin.json
{
  "id": "novachat.translator",
  "name": "Translator",
  "description": "Translate text",
  "version": "0.1.0",
  "author": "NovaChat",
  "configuration": {
    "title": "Translator",
    "properties": {
      "translator.localLanguage": {
        "type": "string",
        "description": "Local language",
        "default": "eng",
        "enum": [
          "cmn",
          "spa",
          "eng",
          "rus",
          "arb",
          "ben",
          "hin",
          "por",
          "ind",
          "jpn",
          "fra",
          "deu",
          "jav",
          "jav",
          "kor",
          "tel",
          "vie",
          "mar",
          "ita",
          "tam",
          "tur",
          "urd",
          "guj",
          "pol",
          "ukr",
          "kan",
          "mai",
          "mal",
          "pes",
          "mya",
          "swh",
          "sun",
          "ron",
          "pan",
          "bho",
          "amh",
          "hau",
          "fuv",
          "bos",
          "bos",
          "hrv",
          "nld",
          "srp",
          "srp",
          "tha",
          "ckb",
          "yor",
          "uzn",
          "uzn",
          "zlm",
          "zlm",
          "ibo",
          "npi",
          "ceb",
          "skr",
          "tgl",
          "hun",
          "azj",
          "azj",
          "sin",
          "koi",
          "ell",
          "ces",
          "mag",
          "run",
          "bel",
          "plt",
          "qug",
          "mad",
          "nya",
          "zyb",
          "pbu",
          "kin",
          "zul",
          "bul",
          "swe",
          "lin",
          "som",
          "hms",
          "hnj",
          "ilo",
          "kaz"
        ],
        "enumDescriptions": [
          "简体中文",
          "Español",
          "English",
          "Русский",
          "العربية الفصحى",
          "বাংলা",
          "हिन्दी",
          "Português",
          "Bahasa Indonesia",
          "日本語",
          "Français",
          "Deutsch",
          "ꦧꦱꦗꦮ",
          "Basa Jawa",
          "한국어",
          "తెలుగు",
          "Tiếng Việt",
          "मराठी",
          "Italiano",
          "தமிழ்",
          "Türkçe",
          "اردو",
          "ગુજરાતી",
          "Polski",
          "Українська",
          "ಕನ್ನಡ",
          "मैथिली",
          "മലയാളം",
          "فارسی",
          "မြန်မာဘာသာ",
          "Kiswahili",
          "Basa Sunda",
          "Română",
          "ਪੰਜਾਬੀ",
          "भोजपुरी",
          "አማርኛ",
          "Hausa",
          "Fulfulde",
          "Босански",
          "Bosanski",
          "Hrvatski",
          "Nederlands",
          "Српски",
          "Srpski",
          "ไทย",
          "کوردیی ناوەندی",
          "Yorùbá",
          "Ўзбек",
          "O'zbek",
          "بهاس ملايو",
          "Bahasa Melayu",
          "Igbo",
          "नेपाली",
          "Cebuano",
          "سرائیکی",
          "Tagalog",
          "Magyar",
          "Азәрбајҹан",
          "Azərbaycan",
          "සිංහල",
          "Коми-Пермяцкӧй",
          "Ελληνικά",
          "Čeština",
          "मगही",
          "Ikirundi",
          "Беларуская",
          "Malagasy",
          "Kichwa",
          "Madhura",
          "Chichewa",
          "Vahcuengh",
          "پښتو",
          "Kinyarwanda",
          "isiZulu",
          "Български",
          "Svenska",
          "Lingála",
          "Soomaali",
          "Hmong Daw",
          "Hmoob Njua",
          "Ilokano",
          "Қазақ"
        ]
      },
      "translator.systemPrompt": {
        "type": "string",
        "description": "System prompt",
        "default": "You are a professional, authentic machine translation engine. Translate the following source text to {{to}}, Output translation directly without any additional text.",
        "format": "markdown"
      },
      "translator.model": {
        "type": "string",
        "description": "Model",
        "format": "model"
      }
    }
  }
}
